# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Python Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Replace 'x' with the specific version you need
        
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Replace with your requirements file if applicable
          
      - name: Run tests
        run: pytest  # Replace with the appropriate command to run your tests
        
      - name: Build package
        run: |
          python setup.py sdist bdist_wheel
          
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release-v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}


